### ISSUE TITLE
Cannot find module 'utilities'

### ISSUE THREAD

**Issue by ryandesign** [jakejs/jake#146]
With nodejs 0.8.6 on OS X 10.8, jake 0.3.9 fails as follows:

```
$ jake

module.js:340
    throw err;
          ^
Error: Cannot find module 'utilities'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/opt/local/lib/node_modules/jake/lib/utils/index.js:23:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
```

jake 0.3.8 works fine.

**Comment by iankitsinghdalal** [comment]
I'm also getting same error. Didn't get any solution yet.
