### ISSUE TITLE
Windows file tasks with drive letter break

### ISSUE THREAD

**Issue by markandrus** [jakejs/jake#318]
Hi!

If you create a `file` task that includes a drive letter, for example

```js
file('C:\foo', function() {
  // Do something
});

task('bar', ['C:\foo']);
```

then trying to run `bar` will fail. I discovered this after writing a bunch of platform-independent code using `path.resolve`, only to find it failed on Windows.

This issue is related to #252, but I think it might warrant a separate ticket since the issue seems more serious than if ":" were simply disallowed in `task`s.

Thanks,
Mark

**Comment by markandrus** [comment]
I think the issue has to do with the way we split on ":" here: https://github.com/jakejs/jake/blob/52a8d98b67394d83502d260b87c59d098b405a3d/lib/namespace.js#L14

**Comment by welearnednothing** [comment]
Thanks Mark! For completeness, can you include a sample error as well?

**Comment by markandrus** [comment]
@welearnednothing sure thing. Here's a sample Jakefile

```js
var fs = require('fs');
var path = require('path');

var foo = path.join(__dirname, 'foo');

file(foo, function() {
  fs.closeSync(fs.openSync(foo, 'w'));
});

task('bar', [foo]);
```

When I run it on Windows, I get

```
C:\Users\mrobe\test-jake>jake bar
jake aborted
Error: Unknown task "C:\Users\mrobe\test-jake\foo"
    at TaskBase.nextPreReq (C:\Users\mrobe\test-jake\node_modules\jake\lib\task\task.js:181:15)
    at TaskBase.runPrereqs (C:\Users\mrobe\test-jake\node_modules\jake\lib\task\task.js:155:14)
(See full trace by running task with --trace)

```

whereas on OS X it works fine.

**Comment by mde** [comment]
@markandrus I've added you to the org -- use your commit-bit powers for good!

**Comment by yosheeck** [comment]
Causing trouble also for me/[us](http://ke.mu) on Windows machines. Just saying it will be useful to have a fix.
